# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/spsur2/smc_rv/smc_rv.cache/wt [current_project]
set_property parent.project_path /home/spsur2/smc_rv/smc_rv.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/spsur2/smc_rv/smc_rv.srcs/sources_1/imports/picorv32/picorv32.v
  /home/spsur2/smc_rv/smc_rv.srcs/sources_1/imports/picorv32/scripts/vivado/tabtest.v
}
synth_design -top top -part xc7k70tfbv676-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
